CREATE TABLE [dbo].[MLModelTable]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY , 
    [UserAlias] NVARCHAR(30) NOT NULL, 
    [DistinctLaborCategories] INT NULL, 
    [NumberOfAdjustedEntries] INT NULL, 
    [RejectedLaborHours] INT NULL, 
    [NumberOfRejectedEntries] INT NULL, 
    [NumberOfEntries] INT NULL, 
    [NumberOfLateEntries] INT NULL, 
    [TimeZoneID] INT NULL, 
    [IsUserExcluded] BIT NULL, 
    [ISEmployeeFTE] BIT NULL, 
    [ApprovedLaborHours] INT NULL, 
    [NumberOfApprovedEntries] INT NULL, 
    [Day9Hours] INT NULL, 
    [Day8Hours] INT NULL, 
    [Day7Hours] INT NULL, 
    [Day6Hours] INT NULL, 
    [Day5Hours] INT NULL, 
    [Day4Hours] INT NULL, 
    [Day3Hours] INT NULL, 
    [Day2Hours] INT NULL, 
    [Day1Hours] INT NULL, 
    [CFApprovedLaborHours] INT NULL, 
    [NumberOfCFApprovedEntries] INT NULL, 
    [Day9CFHours] INT NULL, 
    [Day8CFHours] INT NULL, 
    [Day7CFHours] INT NULL, 
    [Day6CFHours] INT NULL, 
    [Day5CFHours] INT NULL, 
    [Day4CFHours] INT NULL, 
    [Day3CFHours] INT NULL, 
    [Day2CFHours] INT NULL, 
    [Day1CFHours] INT NULL, 
    [Day0CFHours] INT NULL, 
    [Day0Hours] INT NULL 
)


